spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instagram-clone
    username: structure
    password: structure

  data:
    redis:
      host: cache
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create-drop

aws-s3:
  access-key: ${S3_ACCESS_KEY}
  secret-access-key: ${S3_SECRET_ACCESS_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}