spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instagram-clone
    username: structure
    password: structure

  data:
    redis:
      host: cache
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop

aws-s3:
  access-key: ${S3_ACCESS_KEY}
  secret-access-key: ${S3_SECRET_ACCESS_KEY}